/*
#
# Copyright 2007 The Trustees of Indiana University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -----------------------------------------------------------------
#
# Project: HTRC Sloan job submission web interface
# File:  ObjectFactory.java
# Description:  
#
# -----------------------------------------------------------------
# 
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.04 at 07:43:38 PM EST 
//

package edu.indiana.d2i.registryext.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the edu.indiana.d2i.registryext.schema
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Entry_QNAME = new QName(
			"http://registry.htrc.i3.illinois.edu/entities/file", "entry");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: edu.indiana.d2i.registryext.schema
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Entry }
	 * 
	 */
	public Entry createEntry() {
		return new Entry();
	}

	/**
	 * Create an instance of {@link Entries }
	 * 
	 */
	public Entries createEntries() {
		return new Entries();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Entry }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://registry.htrc.i3.illinois.edu/entities/file", name = "entry")
	public JAXBElement<Entry> createEntry(Entry value) {
		return new JAXBElement<Entry>(_Entry_QNAME, Entry.class, null, value);
	}

}
