//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 03:04:47 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://registry.htrc.i3.illinois.edu/entities/file", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.indiana.d2i.registryext.schema;
