//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:21:16 PM EDT 
//

package edu.indiana.d2i.sigiri;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for JobDescriptionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="JobDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.globus.org/namespaces/2004/10/gram/job/description}executable"/>
 *         &lt;element ref="{http://www.globus.org/namespaces/2004/10/gram/job/description}localUserId" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/namespaces/2004/10/gram/job/description}environment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/namespaces/2004/10/gram/job/description}jobType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobDescriptionType", propOrder = { "executable",
		"localUserId", "environment", "jobType" })
public class JobDescriptionType {

	@XmlElement(required = true)
	protected String executable;
	protected String localUserId;
	protected List<NameValuePairType> environment;
	@XmlElement(required = true)
	protected JobTypeEnumeration jobType;

	/**
	 * Gets the value of the executable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExecutable() {
		return executable;
	}

	/**
	 * Sets the value of the executable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExecutable(String value) {
		this.executable = value;
	}

	/**
	 * Gets the value of the localUserId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocalUserId() {
		return localUserId;
	}

	/**
	 * Sets the value of the localUserId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocalUserId(String value) {
		this.localUserId = value;
	}

	/**
	 * Gets the value of the environment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the environment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEnvironment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link NameValuePairType }
	 * 
	 * 
	 */
	public List<NameValuePairType> getEnvironment() {
		if (environment == null) {
			environment = new ArrayList<NameValuePairType>();
		}
		return this.environment;
	}

	/**
	 * Gets the value of the jobType property.
	 * 
	 * @return possible object is {@link JobTypeEnumeration }
	 * 
	 */
	public JobTypeEnumeration getJobType() {
		return jobType;
	}

	/**
	 * Sets the value of the jobType property.
	 * 
	 * @param value
	 *            allowed object is {@link JobTypeEnumeration }
	 * 
	 */
	public void setJobType(JobTypeEnumeration value) {
		this.jobType = value;
	}

}
