//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:21:16 PM EDT 
//


package edu.indiana.d2i.sigiri;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.indiana.d2i.sigiri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Environment_QNAME = new QName("http://www.globus.org/namespaces/2004/10/gram/job/description", "environment");
    private final static QName _JobType_QNAME = new QName("http://www.globus.org/namespaces/2004/10/gram/job/description", "jobType");
    private final static QName _LocalUserId_QNAME = new QName("http://www.globus.org/namespaces/2004/10/gram/job/description", "localUserId");
    private final static QName _Executable_QNAME = new QName("http://www.globus.org/namespaces/2004/10/gram/job/description", "executable");
    private final static QName _Job_QNAME = new QName("http://www.globus.org/namespaces/2004/10/gram/job/description", "job");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.indiana.d2i.sigiri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JobDescriptionType }
     * 
     */
    public JobDescriptionType createJobDescriptionType() {
        return new JobDescriptionType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description", name = "environment")
    public JAXBElement<NameValuePairType> createEnvironment(NameValuePairType value) {
        return new JAXBElement<NameValuePairType>(_Environment_QNAME, NameValuePairType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobTypeEnumeration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description", name = "jobType")
    public JAXBElement<JobTypeEnumeration> createJobType(JobTypeEnumeration value) {
        return new JAXBElement<JobTypeEnumeration>(_JobType_QNAME, JobTypeEnumeration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description", name = "localUserId")
    public JAXBElement<String> createLocalUserId(String value) {
        return new JAXBElement<String>(_LocalUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description", name = "executable")
    public JAXBElement<String> createExecutable(String value) {
        return new JAXBElement<String>(_Executable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description", name = "job")
    public JAXBElement<JobDescriptionType> createJob(JobDescriptionType value) {
        return new JAXBElement<JobDescriptionType>(_Job_QNAME, JobDescriptionType.class, null, value);
    }

}
