//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:21:16 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.indiana.d2i.sigiri;
