//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.14 at 10:56:40 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.globus.org/namespaces/2004/10/gram/job/description")
package edu.indiana.d2i.sloan.schema.user;
