package edu.indiana.d2i.sloan.exception;

public enum ErrorType {
	NOERROR,
	UNKNOWN,
	PATH_NOT_EXIST,
	XML_PARSE_ERROR,
	JOB_DESP_SCHEMA_INVALID,
	JOB_ALREADY_EXIST,
	JOB_NAME_INVALID,
	SIGIRI_SERVICE_UNREACHABLE,
	REGISTRY_SERVICE_UNREACHABLE,
	OAUTH2_SERVICE_UNREACHABLE,
	NULL_EXECUTABLE,
	JOB_DESP_NOT_EXIST,
	JOB_EXE_NOT_EXIST,
	NULL_SIGIRI_JOB_ID;
}
